server:
  port: 80
spring:
  session:
    store-type: redis
  redis:
    database: 1
    host: 140.143.0.227
    password: bigkang
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
        max-active: 8
    timeout: 60000s

